Repository ovrclk/awesome-akash, pull requests merged in 2020-12, with the labels that each got.

#5 ID c8xse9yeozxk71z: Add Uniswap to DeFi apps
  README.md
  uniswap/README.md
  uniswap/deploy.yml
Labels: category/defi

#19 ID g9qjfxwljdyyyd6: Add Jenkins to Continuous Integration
  README.md
  jenkins/README.md
  jenkins/deploy.yaml
Labels: category/ci

#22 ID 7ettq2chho2i5la: Add Pancake Swap to DeFi apps
  README.md
  pancake-swap/README.md
  pancake-swap/deploy.yml
Labels: category/defi

#14 ID dddzdxlvw0fsrv9: Added steemCN to Blogging apps
  README.md
  steemcn/README.md
  steemcn/deploy.yml
Labels: category/blogging

#23 ID e5izjk6jorm2l9z: Add Luaswap
  README.md
  luaswap/README.md
  luaswap/deploy-luaswap.yml
Labels: category/defi

#20 Deployed Uniswap, Pacman, Added and deployed Supermario, pgAdmin4, MongoDB, Caddy WebServer app, ID: 81ow3i7lnhnivs9
  README.md
  caddy/README.md
  caddy/deploy.yml
  mongoDB/README.md
  mongoDB/deploy.yml
  pgadmin4/README.md
  pgadmin4/deploy.yml
  supermario/README.md
  supermario/deploy.yml
Labels: category/database, category/games, category/hosting

#25 ID 32azo0ztv9d7s40: Add DEGO Stats to Tools
  README.md
  dego-stats/README.md
  dego-stats/deploy.yml
Labels: category/defi

#29 ID: 7osljvkpwzp0nu0 Add MyEtherWallet to Wallet
  MyEtherWallet/README.md
  MyEtherWallet/deploy.yml
  README.md
Labels: category/defi, category/wallet

#34 ID ek6kts3ye4rea5u: Adding Dharani to Built with Cosmos-SDK tag
  Dharani/README.md
  Dharani/dharani.yaml
  README.md
Labels: category/defi

#42 ID 8f6afwus2hgd1n1 : Mintr
  README.md
  mintr/README.md
  mintr/deploy-mintr.yml
Labels: category/defi

#46 ID bf1h269owj8j7uh: Add Balancer to DeFi apps
  README.md
  balancer/README.md
  balancer/deploy.yml
Labels: category/defi

#41 ID: 7619g4vil7v5v5e verify tronwallet
  README.md
  tronwallet/README.md
  tronwallet/deploy.yml
Labels: category/defi

#32 ID: 4wjrrrz2vgao522 verify microbox.
  README.md
  microbox/README.md
  microbox/deploy.yml
Labels: category/productivity

#31 ID: bw1hutrojts1iez verify authsteem
  README.md
  authsteem/README.md
  authsteem/deploy.yml
Labels: category/messaging

#51 ID dinx75udn35081o: Add Wordpress to Blogging apps
  README.md
  wordpress/README.md
  wordpress/deploy.yml
Labels: category/blogging

#50 ID:1w3hg0t5tybalkp Deploy Yearn.finance on Akash
  README.md
  Yearn.finance/README.md
  Yearn.finance/deploy-yearn.yml
Labels: category/defi

#60 ID 7ettq2chho2i5la: Add Uma Protocol to DeFi apps
  README.md
  uma-protocol/README.md
  uma-protocol/deploy.yml
Labels: category/defi

#68 ID 81ow3i7lnhnivs9: Add Curve UI app
  README.md
  curve/README.md
  curve/deploy.yml
Labels: category/defi

#85 ID ffu8351zo0royir: Add Adminer to Databases and Administration apps
  README.md
  adminer/README.md
  adminer/deploy.yaml
Labels: category/database

#83 ID avp156ysiljvbjr: Add Synthetix.Exchange to DeFi apps
  README.md
  synthetix.exchange/README.md
  synthetix.exchange/deploy.yml
Labels: category/defi

#115 App MySQL, ID: 81ow3i7lnhnivs9
  MySQL/README.md
  MySQL/deploy.yml
  README.md
Labels: category/database

#116 ID 5bshce3qiky00p0: Add Jira to Project Management
  README.md
  jira/README.md
  jira/deploy.yaml
Labels: category/project-management

#119 ID 5bshce3qiky00p0: Add Confluence Server to Blogging
  README.md
  confluence/README.md
  confluence/deploy.yaml
Labels: category/blogging

#120 Add folding at home - 3bil7g3shkyxq
  README.md
  folding-at-home/README.md
  folding-at-home/folding-at-home.yaml
Labels: category/data-science

#121 ID 5bshce3qiky00p0: Add Bitbucket Server to Continuous Integration
  README.md
  bitbucket/README.md
  bitbucket/deploy.yaml
Labels: category/ci

#122 ID fpszuvlusqdyia2: Add Ren Protocol to DeFi apps
  README.md
  renprotocol/README.md
  renprotocol/deploy.yml
Labels: category/defi

#123 ID b68w7r8c6i67v4c: Add FreeFlix Nucleus to Media apps
  README.md
  freeflix-nucleus/README.md
  freeflix-nucleus/deploy.yml
Labels: category/media

#127 ID 4nr7g1tx3m95mvz : Add Owncloud to Tools apps
  README.md
  owncloud/README.md
  owncloud/owncloud.yml
Labels: category/hosting

#118 ID 2bc6gmdlyjtq51s: Add Grav to Blogging apps
  Grav/README.md
  Grav/deploy.yml
  README.md
Labels: category/blogging

#128 ID ai7mw4cssh0a27k: Add Drupal to Blogging apps
  README.md
  drupal/README.md
  drupal/deploy.yml
Labels: category/blogging

#131 ID 67g42ha79da8pji: Add CouchDB to Databases and Administration apps
  README.md
  couchdb/README.md
  couchdb/deploy.yml
Labels: category/database

#136 ID: 4sg1hzton5xb27q add quill-editor
  README.md
  quill-editor/README.md
  quill-editor/deploy.yml
Labels: category/productivity

#140 ID 5bshce3qiky00p0: Add Mattermost to Chat
  README.md
  mattermost/README.md
  mattermost/deploy.yaml
Labels: category/messaging

#144 ID 2otlcj2ud2dazoo: Add YFII to DeFi apps
  README.md
  yfii/README.md
  yfii/deploy.yml
Labels: category/defi

#145 ID 5bshce3qiky00p0: Add WikiJS to Blogging
  README.md
  wikijs/README.md
  wikijs/deploy.yaml
Labels: category/blogging

#152 ID:d7ixuoxbzxkyfd6 Add dFed To Defi apps
  README.md
  dfed/Readme.md
  dfed/deploy.yml
Labels: category/defi

#155 ID 65osqlsoykh4hfl: Add Memory Game
  MemoryGame/README.md
  MemoryGame/deploy.yml
  README.md
Labels: category/games

#163 ID 7ettq2chho2i5la: Add Redmine
  README.md
  redmine/README.md
  redmine/deploy.yml
Labels: category/project-management

#164 ID 5bshce3qiky00p0: Add UFO Sightings to Data Visualization
  README.md
  ufo-data-vis/README.md
  ufo-data-vis/deploy.yaml
Labels: category/data-visualization
